Car filters
CarFinder/CarFinderClient pull request #13
Opened 2017-10-17 14:31 UTC by AnatolyBelobrovik

Implement car filters form and sorting form.

2017-10-17 14:50 UTC, ElizavetaBuraya approved these changes

2017-10-18 07:22 UTC, AntonNarkevich requested changes
The PR looks good for me except for 2 minor things. Please take a look. And let's merge.

Also, we're going to involve someone to audit the whole FE part soon.

2017-10-18 07:22 UTC, AntonNarkevich commented on src/redux/sagas/carFiltersSaga.ts
> +    // const response = yield call(api.filters.fetchResults, data);
Do we need this comments?

2017-10-18 07:22 UTC, AntonNarkevich commented on src/redux/sagas/carFiltersSaga.ts
> +    // yield put({ type: HERE GOES ACTION, payload: HERE GOES PAYLOAD });
Same.

2017-10-18 07:22 UTC, AntonNarkevich commented on src/utils/carFiltersValidation.ts
> +    errors.yearFrom = 'Please fill in a valid year';
Aren't we using the translations library?

2017-10-18 10:43 UTC, merged